services:
  web:
    build: .
    command: gunicorn core.asgi:application -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --workers 4
    volumes:
      - .:/app
    ports:
      - "8002:8000"
    env_file:
      - .env
    depends_on:
      - db
      - redis

  celery_worker:
    build: .
    command: celery -A core worker -l info
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=${POSTGRES_DB:-risk_network_db}
      - POSTGRES_USER=${POSTGRES_USER:-risk_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-risk_password}

  storm:
    build: ./storm
    ports:
      - "8005:8005"
    restart: unless-stopped

volumes:
  postgres_data: