# Generated by Django 6.1 on 2026-08-16 23:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georisk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='geoevent',
            name='event_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='geoevent',
            name='flood_geojson',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='geoevent',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
        migrations.AddField(
            model_name='geoevent',
            name='streets_geojson',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
