# Generated by Django 6.1 on 2026-08-19 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('georisk', '0002_geoevent_event_date_geoevent_flood_geojson_and_more'),
        ('tweets', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweet',
            name='geo_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tweets', to='georisk.geoevent'),
        ),
    ]
